# Generated by Django 2.0.7 on 2018-09-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='address',
            new_name='last_name',
        ),
    ]
